apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-scheduler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-scheduler
  template:
    metadata:
      labels:
        app: task-scheduler
    spec:
      containers:
      - name: task-scheduler
        image: task-scheduler:latest
        ports:
        - containerPort: 5000

