apiVersion: v1
kind: Service
metadata:
  name: task-scheduler-service
spec:
  selector:
    app: task-scheduler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

